#!/usr/bin/env python3
"""Generate and verify aulycShot icon assets from one geometry source."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
import tempfile
import xml.etree.ElementTree as ET
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
SVG_NAMESPACE = "http://www.w3.org/2000/svg"
MARK_SOURCE = Path("design/iconMark.svg")
MENU_BAR_SVG = Path("design/menuBarIcon.svg")
APP_ICON_SVG = Path("design/appIcon.svg")
MANIFEST = Path("design/icon-assets.generated.json")
GENERATOR_INPUTS = (
    MARK_SOURCE,
    Path("scripts/icon_assets.py"),
    Path("scripts/generate-icon.sh"),
    Path("scripts/render-svg.swift"),
)
APP_ICONSET_FILES = (
    "Contents.json",
    "icon_16.png",
    "icon_16@2x.png",
    "icon_32.png",
    "icon_32@2x.png",
    "icon_128.png",
    "icon_128@2x.png",
    "icon_256.png",
    "icon_256@2x.png",
    "icon_512.png",
    "icon_512@2x.png",
)
GENERATED_OUTPUTS = (
    MENU_BAR_SVG,
    APP_ICON_SVG,
    Path("Resources/AppIcon.icns"),
    *(Path("Resources/Assets.xcassets/AppIcon.appiconset") / name for name in APP_ICONSET_FILES),
)


class IconAssetError(Exception):
    pass


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def atomic_write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(prefix=f".{path.name}-", dir=path.parent)
    temporary = Path(temporary_name)
    try:
        os.fchmod(descriptor, 0o644)
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write(text)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


def normalized_path_data(group: ET.Element, role: str) -> list[str]:
    namespace = f"{{{SVG_NAMESPACE}}}"
    paths = []
    for child in group:
        if child.tag != f"{namespace}path":
            raise IconAssetError(f"{role} group may contain only path elements")
        data = child.get("d")
        if not data:
            raise IconAssetError(f"{role} path has no geometry")
        paths.append(" ".join(data.split()))
    if not paths:
        raise IconAssetError(f"{role} group has no paths")
    return paths


def read_mark(root: Path = ROOT) -> tuple[str, list[str], list[str], str]:
    source = root / MARK_SOURCE
    try:
        document = ET.parse(source)
    except (OSError, ET.ParseError) as exc:
        raise IconAssetError(f"invalid canonical icon mark {source}: {exc}") from exc

    svg = document.getroot()
    if svg.tag != f"{{{SVG_NAMESPACE}}}svg":
        raise IconAssetError("canonical icon mark must be an SVG document")
    view_box = svg.get("viewBox")
    if view_box != "0 0 1024 1024":
        raise IconAssetError("canonical icon mark must use viewBox 0 0 1024 1024")

    namespace = {"svg": SVG_NAMESPACE}
    frame = svg.find("svg:g[@id='frame']", namespace)
    glyph = svg.find("svg:g[@id='glyph']", namespace)
    if frame is None or glyph is None:
        raise IconAssetError("canonical icon mark requires frame and glyph groups")
    allowed_ids = {"frame", "glyph"}
    actual_ids = {group.get("id") for group in svg.findall("svg:g", namespace)}
    if actual_ids != allowed_ids:
        raise IconAssetError("canonical icon mark may contain only frame and glyph groups")

    glyph_transform = glyph.get("transform")
    if not glyph_transform:
        raise IconAssetError("canonical glyph group requires its positioning transform")
    return (
        view_box,
        normalized_path_data(frame, "frame"),
        normalized_path_data(glyph, "glyph"),
        glyph_transform,
    )


def formatted_paths(paths: list[str], indent: str) -> str:
    return "\n".join(f'{indent}<path d="{data}"/>' for data in paths)


def build_svg_documents(root: Path = ROOT) -> tuple[str, str]:
    view_box, frame_paths, glyph_paths, glyph_transform = read_mark(root)
    frame = formatted_paths(frame_paths, "      ")
    glyph = formatted_paths(glyph_paths, "      ")

    menu_bar = f'''<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/icon_assets.py from design/iconMark.svg. Do not edit. -->
<svg xmlns="{SVG_NAMESPACE}" viewBox="{view_box}">
  <g transform="translate(512 512) scale(1.10) translate(-512 -512)">
    <g fill="none" stroke="#000000" stroke-width="58"
       stroke-linecap="round" stroke-linejoin="round">
{frame}
    </g>
    <g transform="{glyph_transform}"
       fill="none" stroke="#000000" stroke-width="64"
       stroke-linecap="round" stroke-linejoin="round">
{glyph}
    </g>
  </g>
</svg>
'''

    app_icon = f'''<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/icon_assets.py from design/iconMark.svg. Do not edit. -->
<svg xmlns="{SVG_NAMESPACE}" viewBox="{view_box}">
  <title>aulycShot hand-drawn app icon</title>
  <rect width="1024" height="1024" fill="#2E2E31"/>
  <g fill="none" stroke="#D8D8DC" stroke-width="29"
     stroke-linecap="round" stroke-linejoin="round">
{frame}
  </g>
  <g transform="{glyph_transform}"
     fill="none" stroke="#D8D8DC" stroke-width="31"
     stroke-linecap="round" stroke-linejoin="round">
{glyph}
  </g>
</svg>
'''
    return menu_bar, app_icon


def generate_svg_files(root: Path = ROOT) -> None:
    menu_bar, app_icon = build_svg_documents(root)
    atomic_write_text(root / MENU_BAR_SVG, menu_bar)
    atomic_write_text(root / APP_ICON_SVG, app_icon)


def file_record(root: Path, relative: Path) -> dict[str, str]:
    path = root / relative
    if not path.is_file():
        raise IconAssetError(f"required icon asset is missing: {relative}")
    return {"file": relative.as_posix(), "sha256": sha256(path)}


def manifest_value(root: Path = ROOT) -> dict[str, object]:
    return {
        "schemaVersion": 1,
        "geometrySource": file_record(root, MARK_SOURCE),
        "generatorInputs": [file_record(root, path) for path in GENERATOR_INPUTS[1:]],
        "generatedOutputs": [file_record(root, path) for path in GENERATED_OUTPUTS],
    }


def write_manifest(root: Path = ROOT) -> None:
    value = manifest_value(root)
    text = json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    atomic_write_text(root / MANIFEST, text)


def verify_assets(root: Path = ROOT) -> None:
    expected_menu_bar, expected_app_icon = build_svg_documents(root)
    for relative, expected in (
        (MENU_BAR_SVG, expected_menu_bar),
        (APP_ICON_SVG, expected_app_icon),
    ):
        path = root / relative
        if not path.is_file() or path.read_text(encoding="utf-8") != expected:
            raise IconAssetError(
                f"generated icon SVG is stale: {relative}; run bash scripts/generate-icon.sh"
            )

    manifest_path = root / MANIFEST
    try:
        recorded = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise IconAssetError(f"invalid generated icon manifest {manifest_path}: {exc}") from exc
    expected_manifest = manifest_value(root)
    if recorded != expected_manifest:
        raise IconAssetError("generated icon assets are stale; run bash scripts/generate-icon.sh")


def make_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)
    subparsers.add_parser("generate-svgs")
    subparsers.add_parser("write-manifest")
    subparsers.add_parser("check")
    return parser


def main() -> int:
    args = make_parser().parse_args()
    try:
        if args.command == "generate-svgs":
            generate_svg_files()
            print("generated menu bar and application icon SVGs")
        elif args.command == "write-manifest":
            write_manifest()
            print("wrote generated icon asset manifest")
        else:
            verify_assets()
            print("icon assets are synchronized")
        return 0
    except (IconAssetError, OSError) as exc:
        print(f"icon asset error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
